### ISSUE TITLE
Readme doesn't mention conda in installation

### ISSUE THREAD

**Issue by kylemath** [NeuroTechX/EEG-ExPy#1]
The readme currently doesn't mention the conda install in installation section, but mentions it later in troubleshooting, 
2) it also mentions pip install ., but doesn't say which requirements.txt file to use
3) I think we want readme to describe install within a virtual environment like:

"To install dependencies within a virtual environment move into directory you cloned and run:

.. code-block:: shell

    $ python3 -m venv venv
    $ source venv/bin/activate
    $ pip install --upgrade pip
    $ pip install ."

**Comment by JohnGriffiths** [comment]
Thanks. 

Installation instructions - particularly cross-platform consistent ones - including the `requirements.txt` and OS-contingencies - is a major priority for ironing out. 
( cc @mhough @JadinTredup  )

The main intended place for the installation instructions is actually in the documentation pages

https://neurotechx.github.io/eeg-notebooks/getting_started/installation.html#

The info in the `README` is supposed to be 'quick' versions of that, but there are inconsistencies. 

To make things easier to manage we could remove installation instructions from the `README` and point to the documentation page. 

In some (currently unlinked) parts of the docs we have full conda installation instructions. 

We do want to support both `conda` and `venv` usage, although want to do so in a way that doesn't make installation instructions complicated. To help with this I set up a 'tabbed' subwindow in the installation page so that we can describe `conda` and `venv` instructions in parallel. 

https://neurotechx.github.io/eeg-notebooks/getting_started/installation.html#installing-the-python-library

But haven't got round to putting the `venv` part in and making consistent with the rest of the instructions. 

Will add add in the `venv` info there asap. Feel free to PR in the meantime if too slow.

**Comment by JadinTredup** [comment]
@JohnGriffiths can I just go ahead and remove the installation instructions on the readme and link to the ones on the DOC page? it seems counter-intuitive to have two separate sets of conflicting instructions.

**Comment by JohnGriffiths** [comment]
Sure go for it.

**Comment by JadinTredup** [comment]
Hey @JohnGriffiths I already chenged the installation instructions last week. Do you want to keep the gettijng started/troubleshooting portions of the README up as well or should they be removed?

**Comment by JohnGriffiths** [comment]
Nah they should be either moved into the main docs or removed

**Comment by JadinTredup** [comment]
@JohnGriffiths check out the new README and docs page and let me know if this works for you.

**Comment by JadinTredup** [comment]
Going to close this one as well since everything has been moved over to the main documentation page where needing Conda is mentioned.
