### ISSUE TITLE
EEG experiments not working with Muse2 via EEG Notebooks on Mac

### ISSUE THREAD

**Issue by kushaalrao** [NeuroTechX/EEG-ExPy#16]
I have created a virtual environment and I am trying to run the SSVEP experiment via EEG notebooks. On my command line, I execute the command "python run_notebook.py" and choose the appropriate device and configurations. It connects to the Muse and the stimulus presentation appears, but it doesn't seem to record and store any of the data and I also get an error at the end "Value error: need at least one array to concatenate". 
![Screen Shot 2020-10-02 at 6 42 26 PM](https://user-images.githubusercontent.com/14986642/94980498-39456780-04df-11eb-88db-8ffac68b7dc2.png)

![Screen Shot 2020-10-02 at 6 43 00 PM](https://user-images.githubusercontent.com/14986642/94980503-42cecf80-04df-11eb-9d4f-a5ebcc71b51c.png)

**Comment by JohnGriffiths** [comment]
Hi Kushal. 

One possibility here is that the experiment setup processes are taking longer than 10s to start, and so the record process is timing out before any data is saved. 

Could you repeat with, say, 30s for the duration option. Same error?

**Comment by JohnGriffiths** [comment]
Also, do you get the same error for all 3 experiment options?

**Comment by JadinTredup** [comment]
Interestingly enough I am getting the exact opposite error now. The data is recording but no stimulus is shown when using the Muse2.

**Comment by JadinTredup** [comment]
@kushaalrao I just pushed a fix that remedied my errors. Could you update and rerun and see if you errors still persist? If so, I can begin to figure out what is wrong there.

**Comment by kushaalrao** [comment]
![Screen Shot 2020-10-21 at 10 19 45 AM](https://user-images.githubusercontent.com/14986642/96755101-1d6b0e00-1387-11eb-82d5-f0c8b1519800.png)
I ran it again with a recording duration of 30 seconds, and it says that it was able to successfully run and record the file. However, I can't seem to access the file. It tells me that permission is denied

**Comment by andraderenew** [comment]
I have the same issue sort of. I get **no file recorded** although the error it outputs is different. And this depends on the mode of execution. Let's be more precise. If I run in terminal 'eegnb runexp -ip' then I input all the values correctly and  I get the PTB sound from psychopy error. 

EEG device successfully connected!
Press [ENTER] when ready to begin...
Traceback (most recent call last):
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/bin/eegnb", line 33, in <module>
    sys.exit(load_entry_point('eeg-notebooks', 'console_scripts', 'eegnb')())
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andraderenew/opt/anaconda3/envs/eeg-notebooks/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/andraderenew/eeg-notebooks/eegnb/cli/__main__.py", line 55, in runexp
    run_introprompt()
  File "/Users/andraderenew/eeg-notebooks/eegnb/cli/introprompt.py", line 132, in main
    run_experiment(experiment, record_duration, eeg_device, save_fn)
  File "/Users/andraderenew/eeg-notebooks/eegnb/cli/utils.py", line 38, in run_experiment
    module.present(duration=record_duration, eeg=eeg_device, save_fn=save_fn)  # type: ignore
  File "/Users/andraderenew/eeg-notebooks/eegnb/experiments/visual_ssvep/ssvep.py", line 20, in present
    record_duration = np.float32(duration)
TypeError: float() argument must be a string or a number, not 'EEG'
0.7603 	WARNING 	PTB audio lib was requested but not loaded: psychtoolbox audio failed to import
0.7863 	WARNING 	For experiments that use audio stimuli, timing will be much better if you upgrade your PsychoPy installation to a 64bit Python3 installation and use the PTB backend.



Also I have in this issue one doubt. **Muse is never connected correctly** although it says here in my code that it connected correctly. 


Also I can point out that if I execute the code from python console then the experiments run and it finishes but it never saves and data recorded. My guess is because it never actually gets connected properly. I do have all libraries required. I even have python 3.7 although I run everything in **ARM processor M chip apple big sur 11.3.1**.

**Comment by ErikBjare** [comment]
@andraderenew Whoops sorry, my bad! 

Fixed in #101, will be merged momentarily.

@kushaalrao If you're still having issues, please reopen the issue with details for the latest version of eeg-notebooks :)

**Comment by andraderenew** [comment]
I don't quite follow! Can anyone explain how will this be solved? Sorry for not knowing much of the dynamics here on github.

**Comment by oreHGA** [comment]
No worries @andraderenew . Your experiment failed to start due to a bug in the code that has now been fixed. Can you try the following:

- Pull/Download the latest version of the eeg-notebooks project again like you did when you first started (this will give you the latest changes that should resolve your issue)

- try running the experiment again.

**Comment by andraderenew** [comment]
ah ok thank you!! I guessed as there were a few files changed 22mins ago that possibly that could be it but I wanted to make sure
