### ISSUE TITLE
Test Experimental Class Structure using EEG

### ISSUE THREAD

**Issue by Parvfect** [NeuroTechX/EEG-ExPy#196]
New Experimental class Structure created through #183 has not been tested using an EEG stream. Needs to be rigirously tested using an EEG to make sure that nothing breaks and all other functions work in the same way.

**Comment by LIN-DN** [comment]
Have you tested the updated code now? Regarding the visualN170 experiment, the documentation does not appear to have updated the case code. n170.present(duration=record_duration, eeg=eeg_device, save_fn=save_fn) module 'eegnb.experiments.visual_n170.n170' has no attribute 'present'.

**Comment by JohnGriffiths** [comment]
Thanks for noting this @LIN-DN . The `.present` method is now replaced with then`run` method. However it sees the example notebook in the `master` branch is still showing the old syntax. In the `develop` branch it is correct. 

@oreHGA @tmorshed @Parvfect I think seeing as this is a key documentation file it should be fixed with a direct commit to `master` rather than waiting for the next merge of `develop` to master. What do you think? Pls check and confirm I got this correct.
